[package]
name = "soundfonts"
version = "0.1.0"
authors = ["Johannes Mueller <github@johannes-mueller.org>"]
edition = "2018"

[dependencies]
itertools = "0.9.0"
wmidi = "3.1.0"
log = "0.4.8"
rand = "0.7.3"
sndfile = "0.0.4"
